### PR TITLE
fix usage with nix 2.15

### LINKED ISSUE #52: nix-build-uncached doesn't build anything with nix 2.15
With the release of Nix 2.15 (see the [release notes](https://nixos.org/manual/nix/stable/release-notes/rl-2.15.html)), this PR was merged: NixOS/nix#7600. As `nix-build-uncached` calls `nix build /nix/store/hash-name.drv`, only the derivations will be built but no outputs. With Nix 2.15 the new syntax `nix build '/nix/store/hash-name.drv^*'` must be used to actually build all outputs.

### PR DESCRIPTION
**Pull request by Artturin**
warning: The interpretation of store paths arguments ending in`.drv` recently changed. If this command is now failing try again with '/nix/store/m5raazy9x0zm8p732y001aqypds0hb2m-gebaar-libinput-+6ce14eb.drv^*'

this will break nix 2.15< but i don't know enough golang to make it conditional so help needed

fixes https://github.com/Mic92/nix-build-uncached/issues/52

There's most likely dozens of silently broken CI right now so it's important to get this in and to nixpkgs

### CODE REVIEW

File: build.go [hunk 1]
```diff
@@ -114,7 +114,7 @@ func nixBuild(drvs map[string]bool, buildArgs []string) error {
 			numChars = numBuildChars
 			args = buildArgs
 		}
-		args = append(args, drv)
+		args = append(args, drv+"^*")
```
Comment (Artturin) [inline build.go]: basically something like this is needed
```suggestion
         if nixVersion >= 2.15 then
		 	args = append(args, drv+"^*")
		else
			args = append(args, drv)
```

**Comment by Mic92** [comment]
bors merge

**Comment by Mic92** [comment]
bors merge
